import type { Category } from './types';
import { TrendingUp, Bitcoin, Landmark, Briefcase, Rocket } from 'lucide-react';

export const categories: Category[] = [
  {
    id: 'stocks',
    name: 'Stocks',
    icon: TrendingUp,
    description: 'Resources for stock market analysis, trading, and news.',
    resources: [
      { id: 's-ex-1', name: 'NYSE', url: 'https://www.nyse.com/', description: 'Major U.S. stock exchange providing real-time trading data and company listings.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 's-ex-2', name: 'NASDAQ', url: 'https://www.nasdaq.com/', description: 'Technology-focused exchange with market insights and stock quotes.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 's-ex-3', name: 'London Stock Exchange', url: 'https://www.londonstockexchange.com/', description: 'Global platform for equity trading with historical data.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 's-ex-4', name: 'Toronto Stock Exchange', url: 'https://www.tsx.com/', description: 'Canadian market hub for stocks and ETFs.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 's-ex-5', name: 'Euronext', url: 'https://www.euronext.com/', description: 'Pan-European exchange network with multi-market access.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 's-web-1', name: 'Yahoo Finance', url: 'https://finance.yahoo.com/', description: 'Offers free stock quotes, news, and analysis tools.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 's-web-2', name: 'Google Finance', url: 'https://www.google.com/finance/', description: 'Provides real-time stock prices and global market data.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 's-web-3', name: 'MarketWatch', url: 'https://www.marketwatch.com/', description: 'Delivers financial news and stock market updates.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 's-web-4', name: 'Investing.com', url: 'https://www.investing.com/', description: 'Features global stock data and economic calendars.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 's-web-5', name: 'Seeking Alpha', url: 'https://seekingalpha.com/', description: 'Community-driven investment analysis with a free tier.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 's-med-1', name: 'CNBC', url: 'https://www.cnbc.com/', description: 'Financial news network with market updates.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 's-med-2', name: 'Bloomberg', url: 'https://www.bloomberg.com/', description: 'Global business and market news with free articles.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 's-med-3', name: 'Financial Times', url: 'https://www.ft.com/', description: 'Business news with limited free access.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 's-med-4', name: 'The Wall Street Journal', url: 'https://www.wsj.com/', description: 'Market insights with some free content.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 's-med-5', name: 'Reuters Finance', url: 'https://www.reuters.com/finance/', description: 'International financial reporting.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 's-app-1', name: 'Robinhood', url: 'https://robinhood.com/', description: 'Commission-free stock trading app.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 's-app-2', name: 'E*TRADE', url: 'https://us.etrade.com/', description: 'Trading and investment platform with robust tools.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 's-app-3', name: 'TD Ameritrade', url: 'https://www.tdameritrade.com/', description: 'Stock trading with educational resources.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 's-app-4', name: 'Webull', url: 'https://www.webull.com/', description: 'Real-time trading and analysis app.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 's-app-5', name: 'Thinkorswim', url: 'https://www.thinkorswim.com/', description: 'Advanced trading platform (free basic version).', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 's-data-1', name: 'Alpha Vantage', url: 'https://www.alphavantage.co/', description: 'Free stock market APIs with real-time data.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 's-data-2', name: 'Quandl', url: 'https://www.quandl.com/', description: 'Financial and economic data with a free tier.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 's-data-3', name: 'IEX Cloud', url: 'https://iexcloud.io/', description: 'Real-time stock data with free basic access.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 's-data-4', name: 'Yahoo Finance API', url: 'https://finance.yahoo.com/', description: 'Public data accessible via scraping tools.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 's-data-5', name: 'FRED', url: 'https://fred.stlouisfed.org/', description: 'Economic data from the Federal Reserve.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 's-tool-1', name: 'TradingView', url: 'https://www.tradingview.com/', description: 'Charting and technical analysis platform.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 's-tool-2', name: 'Finviz', url: 'https://finviz.com/', description: 'Stock screening and market visualization.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 's-tool-3', name: 'Zacks', url: 'https://www.zacks.com/', description: 'Investment research tools (free summaries).', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 's-tool-4', name: 'StockCharts', url: 'https://stockcharts.com/', description: 'Advanced charting with free basics.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 's-tool-5', name: 'Portfolio Visualizer', url: 'https://www.portfoliovisualizer.com/', description: 'Portfolio analysis and backtesting.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 's-edu-1', name: 'Investopedia', url: 'https://www.investopedia.com/', description: 'Comprehensive stock market education.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 's-edu-2', name: 'Khan Academy', url: 'https://www.khanacademy.org/economics-finance-domain', description: 'Free finance and investing courses.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 's-edu-3', name: 'Coursera Financial Markets', url: 'https://www.coursera.org/learn/financial-markets', description: 'Financial markets course from universities.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 's-edu-4', name: 'Morningstar', url: 'https://www.morningstar.com/', description: 'Investment learning (free basics).', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 's-edu-5', name: 'CFA Institute', url: 'https://www.cfainstitute.org/', description: 'Free financial education resources.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 's-com-1', name: 'Reddit r/stocks', url: 'https://www.reddit.com/r/stocks/', description: 'Active investor discussion forum.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 's-com-2', name: 'Wall Street Bets', url: 'https://www.reddit.com/r/wallstreetbets/', description: 'Stock trading community.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 's-com-3', name: 'StockTwits', url: 'https://stocktwits.com/', description: 'Social platform for traders.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 's-com-4', name: 'InvestorVillage', url: 'https://www.investorvillage.com/', description: 'Stock market forums.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 's-com-5', name: 'The Motley Fool Community', url: 'https://www.fool.com/community/', description: 'Investor network and advice.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' }
    ],
  },
  {
    id: 'crypto',
    name: 'Crypto',
    icon: Bitcoin,
    description: 'Your guide to the world of cryptocurrencies and blockchain technology.',
    resources: [
      { id: 'cr-ex-1', name: 'Binance', url: 'https://www.binance.com/', description: 'Global crypto trading platform with extensive coin pairs.', label: '[Exchange]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 'cr-ex-2', name: 'Coinbase', url: 'https://www.coinbase.com/', description: 'User-friendly exchange for beginners and pros.', label: '[Exchange]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 'cr-ex-3', name: 'Kraken', url: 'https://www.kraken.com/', description: 'Secure platform for crypto trading.', label: '[Exchange]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 'cr-ex-4', name: 'Bitfinex', url: 'https://www.bitfinex.com/', description: 'Advanced trading features for professionals.', label: '[Exchange]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 'cr-ex-5', name: 'KuCoin', url: 'https://www.kucoin.com/', description: 'Altcoin-focused exchange with broad listings.', label: '[Exchange]', lastVerified: Date.now(), subcategory: 'Exchanges' },
      { id: 'cr-web-1', name: 'CoinMarketCap', url: 'https://coinmarketcap.com/', description: 'Comprehensive crypto market data and rankings.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'cr-web-2', name: 'CoinGecko', url: 'https://www.coingecko.com/', description: 'Crypto price tracking and market analysis.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'cr-web-3', name: 'CryptoSlate', url: 'https://cryptoslate.com/', description: 'Crypto news and project insights.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'cr-web-4', name: 'Messari', url: 'https://messari.io/', description: 'Crypto research with a free tier.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'cr-web-5', name: 'Blockchain.com', url: 'https://www.blockchain.com/', description: 'Blockchain explorer and wallet services.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'cr-med-1', name: 'CoinDesk', url: 'https://www.coindesk.com/', description: 'Leading crypto news outlet.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'cr-med-2', name: 'CoinTelegraph', url: 'https://cointelegraph.com/', description: 'Blockchain and crypto updates.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'cr-med-3', name: 'Decrypt', url: 'https://decrypt.co/', description: 'Crypto journalism and trends.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'cr-med-4', name: 'The Block', url: 'https://www.theblock.co/', description: 'Industry insights with free articles.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'cr-med-5', name: 'CryptoSlate News', url: 'https://cryptoslate.com/news/', description: 'Market and project news.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'cr-app-1', name: 'Trust Wallet', url: 'https://trustwallet.com/', description: 'Mobile crypto wallet with broad support.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'cr-app-2', name: 'Exodus', url: 'https://www.exodus.com/', description: 'Multi-crypto wallet with user interface.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'cr-app-3', name: 'Blockfolio', url: 'https://blockfolio.com/', description: 'Portfolio tracking for crypto assets.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'cr-app-4', name: 'Crypto.com', url: 'https://crypto.com/', description: 'Trading and payment app with crypto focus.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'cr-app-5', name: 'BitPay', url: 'https://bitpay.com/', description: 'Crypto payment and wallet app.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'cr-wal-1', name: 'Ledger Live', url: 'https://www.ledger.com/ledger-live', description: 'Interface for Ledger hardware wallets.', label: '[Wallet]', lastVerified: Date.now(), subcategory: 'Wallets' },
      { id: 'cr-wal-2', name: 'Trezor Suite', url: 'https://trezor.io/', description: 'Software for Trezor hardware wallets.', label: '[Wallet]', lastVerified: Date.now(), subcategory: 'Wallets' },
      { id: 'cr-wal-3', name: 'Electrum', url: 'https://electrum.org/', description: 'Lightweight Bitcoin wallet.', label: '[Wallet]', lastVerified: Date.now(), subcategory: 'Wallets' },
      { id: 'cr-wal-4', name: 'MyEtherWallet', url: 'https://myetherwallet.com/', description: 'Ethereum wallet for token management.', label: '[Wallet]', lastVerified: Date.now(), subcategory: 'Wallets' },
      { id: 'cr-wal-5', name: 'MetaMask', url: 'https://metamask.io/', description: 'Browser-based Ethereum wallet.', label: '[Wallet]', lastVerified: Date.now(), subcategory: 'Wallets' },
      { id: 'cr-data-1', name: 'Glassnode', url: 'https://glassnode.com/', description: 'On-chain analytics with a free tier.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'cr-data-2', name: 'CryptoCompare', url: 'https://www.cryptocompare.com/', description: 'Crypto data API and market info.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'cr-data-3', name: 'CoinAPI', url: 'https://www.coinapi.io/', description: 'Market data with free tier access.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'cr-data-4', name: 'Nansen', url: 'https://www.nansen.ai/', description: 'Blockchain analytics with free insights.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'cr-data-5', name: 'Etherscan', url: 'https://etherscan.io/', description: 'Ethereum blockchain explorer.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'cr-tool-1', name: 'Coinigy', url: 'https://www.coinigy.com/', description: 'Crypto charting with free basic access.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'cr-tool-2', name: 'Delta', url: 'https://delta.app/', description: 'Portfolio management for crypto assets.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'cr-tool-3', name: 'CryptoPanic', url: 'https://cryptopanic.com/', description: 'Crypto news aggregator.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'cr-tool-4', name: 'Zerion', url: 'https://zerion.io/', description: 'DeFi dashboard and portfolio tracker.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'cr-tool-5', name: 'DeFi Pulse', url: 'https://defipulse.com/', description: 'DeFi metrics and rankings.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'cr-edu-1', name: 'Binance Academy', url: 'https://academy.binance.com/', description: 'Crypto education platform.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'cr-edu-2', name: 'Crypto University', url: 'https://cryptouniversity.co/', description: 'Free crypto courses.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'cr-edu-3', name: 'Coursera Crypto', url: 'https://www.coursera.org/learn/cryptocurrency', description: 'Online crypto learning.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'cr-edu-4', name: 'CoinBureau', url: 'https://coinbureau.com/', description: 'Educational YouTube content on crypto.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'cr-edu-5', name: 'Blockgeeks', url: 'https://blockgeeks.com/', description: 'Blockchain and crypto tutorials.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'cr-com-1', name: 'Reddit r/cryptocurrency', url: 'https://www.reddit.com/r/cryptocurrency/', description: 'Crypto discussion forum.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'cr-com-2', name: 'Bitcoin Talk', url: 'https://bitcointalk.org/', description: 'Bitcoin community hub.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'cr-com-3', name: 'Crypto Twitter', url: 'https://twitter.com/explore/tabs/crypto', description: 'Crypto influencers and news.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'cr-com-4', name: 'Discord Crypto Groups', url: 'https://discord.com/', description: 'Various crypto community servers.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'cr-com-5', name: 'Telegram Crypto Channels', url: 'https://t.me/', description: 'Trading and news groups.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' }
    ],
  },
  {
    id: 'investing',
    name: 'Investing',
    icon: Landmark,
    description: 'General investing principles, strategies, and resources for wealth building.',
    resources: [
      { id: 'i-web-1', name: 'NerdWallet', url: 'https://www.nerdwallet.com/', description: 'Personal finance and investment tools.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'i-web-2', name: 'Bankrate', url: 'https://www.bankrate.com/', description: 'Loan and investment rate comparisons.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'i-web-3', name: 'The Motley Fool', url: 'https://www.fool.com/', description: 'Investment advice with a free tier.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'i-web-4', name: 'Personal Capital', url: 'https://www.personalcapital.com/', description: 'Wealth management and planning.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'i-web-5', name: 'Money Under 30', url: 'https://www.moneyunder30.com/', description: 'Beginner investing guides.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'i-med-1', name: 'Forbes Investing', url: 'https://www.forbes.com/investing/', description: 'Investment-focused business news.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'i-med-2', name: 'Money Magazine', url: 'https://money.com/', description: 'Personal finance and investing updates.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'i-med-3', name: 'Kiplinger', url: 'https://www.kiplinger.com/', description: 'Investment strategy articles.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'i-med-4', name: 'Barron’s', url: 'https://www.barrons.com/', description: 'In-depth market analysis (verify free tier).', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'i-med-5', name: 'Investor’s Business Daily', url: 'https://www.investors.com/', description: 'Stock and investing tips.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'i-app-1', name: 'Acorns', url: 'https://www.acorns.com/', description: 'Micro-investing app for small amounts.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'i-app-2', name: 'Stash', url: 'https://www.stash.com/', description: 'Beginner investment platform.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'i-app-3', name: 'Wealthfront', url: 'https://www.wealthfront.com/', description: 'Robo-advisor for automated investing.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'i-app-4', name: 'Betterment', url: 'https://www.betterment.com/', description: 'Automated investment management.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'i-app-5', name: 'SoFi Invest', url: 'https://www.sofi.com/invest/', description: 'Investment app with diverse options.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'i-data-1', name: 'World Bank Data', url: 'https://data.worldbank.org/', description: 'Global economic indicators.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'i-data-2', name: 'OECD Data', url: 'https://data.oecd.org/', description: 'International financial statistics.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'i-data-3', name: 'Statista', url: 'https://www.statista.com/', description: 'Market research with a free tier.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'i-data-4', name: 'Trading Economics', url: 'https://tradingeconomics.com/', description: 'Economic and market data.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'i-data-5', name: 'FRED', url: 'https://fred.stlouisfed.org/', description: 'Federal Reserve economic data.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'i-tool-1', name: 'Morningstar Portfolio Tools', url: 'https://www.morningstar.com/', description: 'Investment analysis tools.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'i-tool-2', name: 'YCharts', url: 'https://ycharts.com/', description: 'Financial data visualization (free trial).', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'i-tool-3', name: 'Personal Capital Dashboard', url: 'https://www.personalcapital.com/', description: 'Net worth and investment tracking.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'i-tool-4', name: 'Mint', url: 'https://www.mint.com/', description: 'Budgeting and investment tools.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'i-tool-5', name: 'Empower', url: 'https://www.empower.com/', description: 'Retirement planning and analysis.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'i-edu-1', name: 'The Balance', url: 'https://www.thebalance.com/', description: 'Investing guides for all levels.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'i-edu-2', name: 'SmartAsset', url: 'https://smartasset.com/', description: 'Financial planning education.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'i-edu-3', name: 'Udemy Investing Courses', url: 'https://www.udemy.com/topic/investing/', description: 'Online investing courses.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'i-edu-4', name: 'EdX Finance', url: 'https://www.edx.org/learn/finance', description: 'Free finance courses.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'i-edu-5', name: 'Bogleheads', url: 'https://www.bogleheads.org/', description: 'Passive investing resources.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'i-com-1', name: 'Reddit r/investing', url: 'https://www.reddit.com/r/investing/', description: 'Investment discussion forum.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'i-com-2', name: 'Bogleheads Forum', url: 'https://www.bogleheads.org/forum/', description: 'Passive investing community.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'i-com-3', name: 'MoneyTalk', url: 'https://www.moneytalk.org/', description: 'Financial advice network.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'i-com-4', name: 'Wealthsimple Community', url: 'https://www.wealthsimple.com/en-ca/community', description: 'Investor support group.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'i-com-5', name: 'Quora Investing', url: 'https://www.quora.com/topic/Investing', description: 'Q&A platform for investing.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
    ],
  },
  {
    id: 'pe-vc',
    name: 'PE / VC',
    icon: Briefcase,
    description: 'Insights into private equity, venture capital, and startup funding.',
    resources: [
      { id: 'pe-web-1', name: 'PitchBook', url: 'https://pitchbook.com/', description: 'PE/VC data with free summaries.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'pe-web-2', name: 'Preqin', url: 'https://www.preqin.com/', description: 'Alternative assets data with free insights.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'pe-web-3', name: 'CB Insights', url: 'https://www.cbinsights.com/', description: 'VC trends with free reports.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'pe-web-4', name: 'AngelList', url: 'https://angel.co/', description: 'Startup and VC platform.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'pe-web-5', name: 'Crunchbase', url: 'https://www.crunchbase.com/', description: 'Company funding and VC data.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'pe-med-1', name: 'PE Hub', url: 'https://www.pehub.com/', description: 'PE news and analysis.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'pe-med-2', name: 'VentureBeat', url: 'https://venturebeat.com/', description: 'VC and startup news.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'pe-med-3', name: 'TechCrunch', url: 'https://techcrunch.com/', description: 'Startup and VC coverage.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'pe-med-4', name: 'Axios Pro Rata', url: 'https://www.axios.com/pro-rata/', description: 'Deal flow insights (free tier).', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'pe-med-5', name: 'Private Equity International', url: 'https://www.privateequityinternational.com/', description: 'PE industry updates.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'pe-app-1', name: 'Carta', url: 'https://carta.com/', description: 'Equity management for startups and VCs.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'pe-app-2', name: 'Capshare', url: 'https://www.capshare.com/', description: 'Cap table and equity software.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'pe-app-3', name: 'eFront', url: 'https://www.efront.com/', description: 'PE portfolio management (demo available).', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'pe-app-4', name: 'Altvia', url: 'https://www.altvia.com/', description: 'VC/PE CRM with free overview.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'pe-app-5', name: 'DealCloud', url: 'https://www.dealcloud.com/', description: 'Deal sourcing and management.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'pe-data-1', name: 'SEC EDGAR', url: 'https://www.sec.gov/edgar', description: 'Public PE/VC filings and disclosures.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'pe-data-2', name: 'S&P Capital IQ', url: 'https://www.capitaliq.com/', description: 'Financial data with free snippets.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'pe-data-3', name: 'PitchBook Data', url: 'https://pitchbook.com/data', description: 'PE/VC analytics (free tier).', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'pe-data-4', name: 'Dealogic', url: 'https://www.dealogic.com/', description: 'M&A and PE data (limited free access).', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'pe-data-5', name: 'Preqin Data', url: 'https://www.preqin.com/', description: 'Alternative investment data.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'pe-tool-1', name: 'Intralinks', url: 'https://www.intralinks.com/', description: 'Deal management with free demo.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'pe-tool-2', name: 'Colmore', url: 'https://www.colmore.com/', description: 'PE/VC analytics platform.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'pe-tool-3', name: 'Visually', url: 'https://www.visually.io/', description: 'Data visualization for PE.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'pe-tool-4', name: 'FundCount', url: 'https://www.fundcount.com/', description: 'Fund accounting tool (free trial).', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'pe-tool-5', name: 'Burgiss', url: 'https://www.burgiss.com/', description: 'Private capital analysis.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'pe-edu-1', name: 'Harvard Business Review', url: 'https://hbr.org/', description: 'PE/VC articles (some free).', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'pe-edu-2', name: 'Kauffman Foundation', url: 'https://www.kauffman.org/', description: 'Entrepreneurship education.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'pe-edu-3', name: 'Stanford GSB', url: 'https://www.gsb.stanford.edu/', description: 'Free VC case studies.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'pe-edu-4', name: 'Entrepreneur', url: 'https://www.entrepreneur.com/', description: 'Startup funding guides.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'pe-edu-5', name: 'VC University', url: 'https://vcuniversity.com/', description: 'VC training (free basics).', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'pe-com-1', name: 'Reddit r/venturecapital', url: 'https://www.reddit.com/r/venturecapital/', description: 'VC discussion forum.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'pe-com-2', name: 'Angel Capital Association', url: 'https://www.angelcapitalassociation.org/', description: 'Angel investor network.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'pe-com-3', name: 'Y Combinator Community', url: 'https://www.ycombinator.com/', description: 'Startup/VC forum.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'pe-com-4', name: 'LinkedIn PE/VC Groups', url: 'https://www.linkedin.com/', description: 'Professional networks.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'pe-com-5', name: 'Private Equity Insider', url: 'https://www.privateequityinfo.com/', description: 'Industry community.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
    ],
  },
  {
    id: 'fintech',
    name: 'Fintech',
    icon: Rocket,
    description: 'Exploring the intersection of finance and technology.',
    resources: [
      { id: 'ft-web-1', name: 'Fintech Weekly', url: 'https://www.fintechweekly.com/', description: 'Directory of fintech companies.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'ft-web-2', name: 'Let’s Talk Payments', url: 'https://www.letstalkpayments.com/', description: 'Fintech news and trends.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'ft-web-3', name: 'Finextra', url: 'https://www.finextra.com/', description: 'Fintech industry updates.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'ft-web-4', name: 'Crowdfund Insider', url: 'https://www.crowdfundinsider.com/', description: 'Crowdfunding insights.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'ft-web-5', name: 'The Paypers', url: 'https://thepaypers.com/', description: 'Payment technology news.', label: '[Website]', lastVerified: Date.now(), subcategory: 'Websites' },
      { id: 'ft-med-1', name: 'Fintech Futures', url: 'https://www.fintechfutures.com/', description: 'Trusted fintech news platform.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'ft-med-2', name: 'PYMNTS', url: 'https://www.pymnts.com/', description: 'Fintech payments journalism.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'ft-med-3', name: 'Tearsheet', url: 'https://tearsheet.co/', description: 'In-depth fintech analysis.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'ft-med-4', name: 'Banking Technology', url: 'https://www.bankingtech.com/', description: 'Banking tech insights.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'ft-med-5', name: 'Fintech Magazine', url: 'https://fintechmagazine.com/', description: 'Industry trends and news.', label: '[Media]', lastVerified: Date.now(), subcategory: 'Media' },
      { id: 'ft-app-1', name: 'PayPal', url: 'https://www.paypal.com/', description: 'Payment processing app.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'ft-app-2', name: 'Square', url: 'https://squareup.com/', description: 'Small business fintech solution.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'ft-app-3', name: 'Stripe', url: 'https://stripe.com/', description: 'Payment infrastructure for developers.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'ft-app-4', name: 'Revolut', url: 'https://www.revolut.com/', description: 'Multi-currency banking app.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'ft-app-5', name: 'Chime', url: 'https://www.chime.com/', description: 'Fee-free banking app.', label: '[App]', lastVerified: Date.now(), subcategory: 'Applications' },
      { id: 'ft-data-1', name: 'Open Banking Directory', url: 'https://www.openbanking.org.uk/', description: 'UK open data.', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'ft-data-2', name: 'Plaid', url: 'https://plaid.com/', description: 'Financial API data (free tier).', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'ft-data-3', name: 'Xignite', url: 'https://www.xignite.com/', description: 'Market data API (free trial).', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'ft-data-4', name: 'Finicity', url: 'https://www.finicity.com/', description: 'Financial data (free overview).', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'ft-data-5', name: 'Yodlee', url: 'https://www.yodlee.com/', description: 'Consumer finance data (free insights).', label: '[Data Source]', lastVerified: Date.now(), subcategory: 'Data Sources' },
      { id: 'ft-tool-1', name: 'Lemonade', url: 'https://www.lemonade.com/', description: 'Insurtech platform.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'ft-tool-2', name: 'Kabbage', url: 'https://www.kabbage.com/', description: 'Small business loans.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'ft-tool-3', name: 'Zelle', url: 'https://www.zellepay.com/', description: 'Peer-to-peer payments.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'ft-tool-4', name: 'Wise', url: 'https://wise.com/', description: 'International transfers.', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'ft-tool-5', name: 'Adyen', url: 'https://www.adyen.com/', description: 'Payment processing (free demo).', label: '[Tool]', lastVerified: Date.now(), subcategory: 'Tools' },
      { id: 'ft-edu-1', name: 'Fintech School', url: 'https://www.fintechschool.com/', description: 'Online courses.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'ft-edu-2', name: 'MIT Fintech', url: 'https://fintech.mit.edu/', description: 'Research and education.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'ft-edu-3', name: 'Oxford Fintech Programme', url: 'https://www.ox.ac.uk/', description: 'Free webinars.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'ft-edu-4', name: 'Accenture Fintech Insights', url: 'https://www.accenture.com/', description: 'Industry reports.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'ft-edu-5', name: 'EY Fintech', url: 'https://www.ey.com/en_gl/fintech', description: 'Thought leadership.', label: '[Educational Resource]', lastVerified: Date.now(), subcategory: 'Educational Resources' },
      { id: 'ft-com-1', name: 'Reddit r/fintech', url: 'https://www.reddit.com/r/fintech/', description: 'Fintech discussions.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'ft-com-2', name: 'Fintech Forum', url: 'https://www.fintechforum.org/', description: 'Industry network.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'ft-com-3', name: 'LinkedIn Fintech Groups', url: 'https://www.linkedin.com/', description: 'Professional circles.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'ft-com-4', name: 'Fintech Meetups', url: 'https://www.meetup.com/topics/fintech/', description: 'Local events.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
      { id: 'ft-com-5', name: 'Slack Fintech Communities', url: 'https://finos.org/', description: 'Collaboration spaces.', label: '[Community]', lastVerified: Date.now(), subcategory: 'Communities' },
    ],
  },
];

export const getCategories = (): Omit<Category, 'resources'>[] => {
  return categories.map(({ resources, ...category }) => category);
};

export const getCategoryWithResources = (id: string): Category | undefined => {
  return categories.find((category) => category.id === id);
};
